import {Alert, Share} from 'react-native';
import type {
  AnalyticsEvent,
  ConsoleLog,
  CrashRecord,
  NetworkLog,
  PushNotificationRecord,
  ReduxHistoryEntry,
} from '../types';
import {formatDateTime, getCurlCommand} from './index';

function safeStringify(data: any): string {
  if (data === undefined) return 'undefined';
  if (data === null) return 'null';
  if (typeof data === 'string') return data;
  try {
    return JSON.stringify(data, null, 2);
  } catch {
    return String(data);
  }
}

/**
 * Constructs a beautifully formatted markdown/text report for an API Network Log.
 */
export function formatApiReport(log: NetworkLog): string {
  const method = (log.method || 'GET').toUpperCase();
  const statusStr =
    log.status === 0
      ? 'Failed / Network Error'
      : log.status != null
      ? `${log.status} ${log.status === 200 ? 'OK' : ''}`.trim()
      : 'Pending';
  const durationStr = log.duration != null ? `${log.duration}ms` : 'N/A';
  const timeStr = formatDateTime(log.startTime || Date.now());
  const curlCmd = getCurlCommand(log);

  const lines: string[] = [
    '🚀 API INSPECTION REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Method:   ${method}`,
    `📊 Status:   ${statusStr}`,
    `⏱️ Duration: ${durationStr}`,
    `🕒 Time:     ${timeStr}`,
  ];

  if (log.client) {
    lines.push(`🔌 Client:   ${log.client.toUpperCase()}`);
  }

  lines.push(`🌐 URL:      ${log.url || 'N/A'}`);
  lines.push('');

  if (log.requestHeaders && Object.keys(log.requestHeaders).length > 0) {
    lines.push('📋 Request Headers:');
    lines.push(safeStringify(log.requestHeaders));
    lines.push('');
  }

  if (log.request != null && log.request !== '') {
    lines.push('📝 Request Body:');
    lines.push(safeStringify(log.request));
    lines.push('');
  }

  if (log.responseHeaders && Object.keys(log.responseHeaders).length > 0) {
    lines.push('📑 Response Headers:');
    lines.push(safeStringify(log.responseHeaders));
    lines.push('');
  }

  if (log.response != null && log.response !== '') {
    lines.push('📥 Response Data:');
    lines.push(safeStringify(log.response));
    lines.push('');
  }

  if (curlCmd) {
    lines.push('💻 cURL Command:');
    lines.push(curlCmd);
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for a Push Notification.
 */
export function formatPushReport(record: PushNotificationRecord): string {
  const timeStr = formatDateTime(record.timestamp || Date.now());
  const sourceStr = (record.source || 'push').toUpperCase();
  const appStateStr = (record.appState || 'unknown').toUpperCase();
  const actionStr = (record.action || 'received').toUpperCase();

  const lines: string[] = [
    '🔔 PUSH NOTIFICATION REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Title:     ${record.title || '(No Title)'}`,
    `📝 Body:      ${record.body || '(No Body)'}`,
    `🏢 Source:    ${sourceStr}${record.domain ? ` (${record.domain})` : ''}`,
    `🆔 Message ID: ${record.id || 'N/A'}`,
    `📱 App State: ${appStateStr}`,
    `🎯 Action:    ${actionStr}`,
    `🕒 Time:      ${timeStr}`,
  ];

  if (record.subtitle) {
    lines.push(`📑 Subtitle:  ${record.subtitle}`);
  }
  if (record.channelId) {
    lines.push(`🏷️ Channel:   ${record.channelId}`);
  }
  if (record.priority) {
    lines.push(`⚡ Priority:  ${record.priority}`);
  }
  if (record.badge != null) {
    lines.push(`🔢 Badge:     ${record.badge}`);
  }
  if (record.sound) {
    lines.push(`🔊 Sound:     ${record.sound}`);
  }
  if (record.imageUrl) {
    lines.push(`🖼️ Image:     ${record.imageUrl}`);
  }

  lines.push('');

  if (record.data && Object.keys(record.data).length > 0) {
    lines.push('📦 Custom Data Payload:');
    lines.push(safeStringify(record.data));
    lines.push('');
  }

  if (record.customDomainAttributes && Object.keys(record.customDomainAttributes).length > 0) {
    lines.push('🏢 Domain Attributes:');
    lines.push(safeStringify(record.customDomainAttributes));
    lines.push('');
  }

  if (record.rawPayload != null) {
    lines.push('⚙️ Raw Payload:');
    lines.push(safeStringify(record.rawPayload));
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for a Crash Log.
 */
export function formatCrashReport(crash: CrashRecord): string {
  const timeStr = `${crash.dateStr || ''} ${crash.timeStr || ''}`.trim() || formatDateTime(crash.timestamp);
  const lines: string[] = [
    '💥 CRASH REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `⚠️ Error:   ${crash.name || 'Error'}: ${crash.message || 'Unknown error'}`,
    `🚨 Fatal:   ${crash.isFatal ? 'YES (Fatal)' : 'NO (Caught)'}`,
    `🏷️ Type:    ${(crash.type || 'js').toUpperCase()}`,
    `🕒 Time:    ${timeStr}`,
  ];

  if (crash.deviceInfo) {
    lines.push(`📱 Platform: ${crash.deviceInfo.platform || 'N/A'} (OS: ${crash.deviceInfo.osVersion || 'N/A'}, RN: ${crash.deviceInfo.rnVersion || 'N/A'})`);
  }
  if (crash.memoryInfo?.usedJSHeapSize) {
    lines.push(`💾 Used Heap: ${Math.round(crash.memoryInfo.usedJSHeapSize / (1024 * 1024))} MB`);
  }

  lines.push('');

  if (crash.stack) {
    lines.push('📜 Stack Trace:');
    lines.push(crash.stack);
    lines.push('');
  }

  if (crash.breadcrumbs && crash.breadcrumbs.length > 0) {
    lines.push(`🐾 Breadcrumbs (${crash.breadcrumbs.length}):`);
    crash.breadcrumbs.slice(-10).forEach(b => {
      lines.push(`  • [${b.type}] ${b.message} (${formatDateTime(b.timestamp)})`);
    });
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for an Analytics Event.
 */
export function formatAnalyticsReport(event: AnalyticsEvent): string {
  const timeStr = formatDateTime(event.timestamp);
  const lines: string[] = [
    '📊 ANALYTICS EVENT REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Event Name:   ${event.name || 'Unknown'}`,
    `🏢 Source:       ${(event.source || 'manual').toUpperCase()}`,
    `🕒 Timestamp:    ${timeStr}`,
  ];

  if (event.screenName) lines.push(`📱 Screen Name:  ${event.screenName}`);
  if (event.userId) lines.push(`👤 User ID:      ${event.userId}`);
  if (event.trackingId) lines.push(`🆔 Tracking ID:  ${event.trackingId}`);

  lines.push('');

  if (event.params && Object.keys(event.params).length > 0) {
    lines.push('📦 Event Parameters:');
    lines.push(safeStringify(event.params));
    lines.push('');
  }

  if (event.userProperties && Object.keys(event.userProperties).length > 0) {
    lines.push('👤 User Properties:');
    lines.push(safeStringify(event.userProperties));
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for a Redux Action.
 */
export function formatReduxReport(action: ReduxHistoryEntry): string {
  const timeStr = typeof action.timestamp === 'number' ? formatDateTime(action.timestamp) : action.timestamp;
  const lines: string[] = [
    '🔄 REDUX ACTION REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Action Type: ${action.type || 'UNKNOWN'}`,
    `🕒 Timestamp:   ${timeStr}`,
  ];

  if (action.caller) lines.push(`📍 Caller:      ${action.caller}`);
  if (action.originType) lines.push(`⚙️ Origin:      ${action.originType}`);
  if (action.affectedSlices && action.affectedSlices.length > 0) {
    lines.push(`🍰 Slices:      ${action.affectedSlices.join(', ')}`);
  }

  lines.push('');
  lines.push('📦 Action Payload:');
  lines.push(safeStringify(action.payload));
  lines.push('');

  if (action.prevState !== undefined) {
    lines.push('⏮️ Previous State:');
    lines.push(safeStringify(action.prevState));
    lines.push('');
  }

  if (action.nextState !== undefined) {
    lines.push('⏭️ Next State:');
    lines.push(safeStringify(action.nextState));
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for a Console Log.
 */
export function formatLogReport(log: ConsoleLog): string {
  const timeStr = formatDateTime(log.timestamp);
  const lines: string[] = [
    '📜 CONSOLE LOG REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Level:     ${(log.type || 'info').toUpperCase()}`,
    `🕒 Timestamp: ${timeStr}`,
    `💬 Message:   ${log.message || ''}`,
  ];

  if (log.caller) lines.push(`📍 Caller:    ${log.caller}`);

  lines.push('');

  if (log.rawArgs && log.rawArgs.length > 0) {
    lines.push('📦 Arguments:');
    lines.push(safeStringify(log.rawArgs));
    lines.push('');
  }

  if (log.stack || log.errorStack) {
    lines.push('📜 Stack Trace:');
    lines.push(log.stack || log.errorStack || '');
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Universal Native Share Executor
 */
async function triggerNativeShare(title: string, message: string): Promise<void> {
  try {
    await Share.share(
      {
        title,
        message,
      },
      {
        dialogTitle: title,
      },
    );
  } catch (error: any) {
    if (error?.message !== 'User did not share') {
      Alert.alert('Share Error', error?.message || 'Failed to open share sheet');
    }
  }
}

export async function shareApiReport(log: NetworkLog): Promise<void> {
  const message = formatApiReport(log);
  const title = `API: ${log.method || 'GET'} ${log.url?.substring(0, 40) || ''}`;
  await triggerNativeShare(title, message);
}

export async function sharePushReport(record: PushNotificationRecord): Promise<void> {
  const message = formatPushReport(record);
  const title = `Push: ${record.title || record.id || 'Notification'}`;
  await triggerNativeShare(title, message);
}

export async function shareCrashReport(crash: CrashRecord): Promise<void> {
  const message = formatCrashReport(crash);
  const title = `Crash: ${crash.name || crash.message || 'Error'}`;
  await triggerNativeShare(title, message);
}

export async function shareAnalyticsReport(event: AnalyticsEvent): Promise<void> {
  const message = formatAnalyticsReport(event);
  const title = `Analytics: ${event.name || 'Event'}`;
  await triggerNativeShare(title, message);
}

export async function shareReduxReport(action: ReduxHistoryEntry): Promise<void> {
  const message = formatReduxReport(action);
  const title = `Redux: ${action.type || 'Action'}`;
  await triggerNativeShare(title, message);
}

export async function shareLogReport(log: ConsoleLog): Promise<void> {
  const message = formatLogReport(log);
  const title = `Log: ${(log.type || 'info').toUpperCase()} - ${log.message?.substring(0, 30) || ''}`;
  await triggerNativeShare(title, message);
}
