import {Alert, Share} from 'react-native';
import {writeNativeExportFile, shareNativeFile} from '../native/NativeInspector';
import type {
  AnalyticsEvent,
  ConsoleLog,
  CrashRecord,
  NetworkLog,
  PushNotificationRecord,
  ReduxHistoryEntry,
  SocketConnectionRecord,
} from '../types';
import {formatDateTime, getCurlCommand} from './index';

function safeStringify(data: any): string {
  if (data === undefined) return 'undefined';
  if (data === null) return 'null';
  if (typeof data === 'string') return data;
  try {
    return JSON.stringify(data, null, 2);
  } catch {
    return String(data);
  }
}

/**
 * Constructs a beautifully formatted markdown/text report for an API Network Log.
 */
export function formatApiReport(log: NetworkLog): string {
  const method = (log.method || 'GET').toUpperCase();
  const statusStr =
    log.status === 0
      ? 'Failed / Network Error'
      : log.status != null
      ? `${log.status} ${log.status === 200 ? 'OK' : ''}`.trim()
      : 'Pending';
  const durationStr = log.duration != null ? `${log.duration}ms` : 'N/A';
  const timeStr = formatDateTime(log.startTime || Date.now());
  const curlCmd = getCurlCommand(log);

  const lines: string[] = [
    '🚀 API INSPECTION REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Method:   ${method}`,
    `📊 Status:   ${statusStr}`,
    `⏱️ Duration: ${durationStr}`,
    `🕒 Time:     ${timeStr}`,
  ];

  if (log.client) {
    lines.push(`🔌 Client:   ${log.client.toUpperCase()}`);
  }

  lines.push(`🌐 URL:      ${log.url || 'N/A'}`);
  lines.push('');

  if (log.requestHeaders && Object.keys(log.requestHeaders).length > 0) {
    lines.push('📋 Request Headers:');
    lines.push(safeStringify(log.requestHeaders));
    lines.push('');
  }

  if (log.request != null && log.request !== '') {
    lines.push('📝 Request Body:');
    lines.push(safeStringify(log.request));
    lines.push('');
  }

  if (log.responseHeaders && Object.keys(log.responseHeaders).length > 0) {
    lines.push('📑 Response Headers:');
    lines.push(safeStringify(log.responseHeaders));
    lines.push('');
  }

  if (log.response != null && log.response !== '') {
    lines.push('📥 Response Data:');
    lines.push(safeStringify(log.response));
    lines.push('');
  }

  if (curlCmd) {
    lines.push('💻 cURL Command:');
    lines.push(curlCmd);
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for a Push Notification.
 */
export function formatPushReport(record: PushNotificationRecord): string {
  const timeStr = formatDateTime(record.timestamp || Date.now());
  const sourceStr = (record.source || 'push').toUpperCase();
  const appStateStr = (record.appState || 'unknown').toUpperCase();
  const actionStr = (record.action || 'received').toUpperCase();

  const lines: string[] = [
    '🔔 PUSH NOTIFICATION REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Title:     ${record.title || '(No Title)'}`,
    `📝 Body:      ${record.body || '(No Body)'}`,
    `🏢 Source:    ${sourceStr}${record.domain ? ` (${record.domain})` : ''}`,
    `🆔 Message ID: ${record.id || 'N/A'}`,
    `📱 App State: ${appStateStr}`,
    `🎯 Action:    ${actionStr}`,
    `🕒 Time:      ${timeStr}`,
  ];

  if (record.subtitle) {
    lines.push(`📑 Subtitle:  ${record.subtitle}`);
  }
  if (record.channelId) {
    lines.push(`🏷️ Channel:   ${record.channelId}`);
  }
  if (record.priority) {
    lines.push(`⚡ Priority:  ${record.priority}`);
  }
  if (record.badge != null) {
    lines.push(`🔢 Badge:     ${record.badge}`);
  }
  if (record.sound) {
    lines.push(`🔊 Sound:     ${record.sound}`);
  }
  if (record.imageUrl) {
    lines.push(`🖼️ Image:     ${record.imageUrl}`);
  }

  lines.push('');

  if (record.data && Object.keys(record.data).length > 0) {
    lines.push('📦 Custom Data Payload:');
    lines.push(safeStringify(record.data));
    lines.push('');
  }

  if (record.customDomainAttributes && Object.keys(record.customDomainAttributes).length > 0) {
    lines.push('🏢 Domain Attributes:');
    lines.push(safeStringify(record.customDomainAttributes));
    lines.push('');
  }

  if (record.rawPayload != null) {
    lines.push('⚙️ Raw Payload:');
    lines.push(safeStringify(record.rawPayload));
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for a Crash Log.
 */
export function formatCrashReport(crash: CrashRecord): string {
  const timeStr = `${crash.dateStr || ''} ${crash.timeStr || ''}`.trim() || formatDateTime(crash.timestamp);
  const lines: string[] = [
    '💥 CRASH REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `⚠️ Error:   ${crash.name || 'Error'}: ${crash.message || 'Unknown error'}`,
    `🚨 Fatal:   ${crash.isFatal ? 'YES (Fatal)' : 'NO (Caught)'}`,
    `🏷️ Type:    ${(crash.type || 'js').toUpperCase()}`,
    `🕒 Time:    ${timeStr}`,
  ];

  if (crash.deviceInfo) {
    lines.push(`📱 Platform: ${crash.deviceInfo.platform || 'N/A'} (OS: ${crash.deviceInfo.osVersion || 'N/A'}, RN: ${crash.deviceInfo.rnVersion || 'N/A'})`);
  }
  if (crash.memoryInfo?.usedJSHeapSize) {
    lines.push(`💾 Used Heap: ${Math.round(crash.memoryInfo.usedJSHeapSize / (1024 * 1024))} MB`);
  }

  lines.push('');

  if (crash.stack) {
    lines.push('📜 Stack Trace:');
    lines.push(crash.stack);
    lines.push('');
  }

  if (crash.breadcrumbs && crash.breadcrumbs.length > 0) {
    lines.push(`🐾 Breadcrumbs (${crash.breadcrumbs.length}):`);
    crash.breadcrumbs.slice(-10).forEach(b => {
      lines.push(`  • [${b.type}] ${b.message} (${formatDateTime(b.timestamp)})`);
    });
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for an Analytics Event.
 */
export function formatAnalyticsReport(event: AnalyticsEvent): string {
  const timeStr = formatDateTime(event.timestamp);
  const lines: string[] = [
    '📊 ANALYTICS EVENT REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Event Name:   ${event.name || 'Unknown'}`,
    `🏢 Source:       ${(event.source || 'manual').toUpperCase()}`,
    `🕒 Timestamp:    ${timeStr}`,
  ];

  if (event.screenName) lines.push(`📱 Screen Name:  ${event.screenName}`);
  if (event.userId) lines.push(`👤 User ID:      ${event.userId}`);
  if (event.trackingId) lines.push(`🆔 Tracking ID:  ${event.trackingId}`);

  lines.push('');

  if (event.params && Object.keys(event.params).length > 0) {
    lines.push('📦 Event Parameters:');
    lines.push(safeStringify(event.params));
    lines.push('');
  }

  if (event.userProperties && Object.keys(event.userProperties).length > 0) {
    lines.push('👤 User Properties:');
    lines.push(safeStringify(event.userProperties));
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for a Redux Action.
 */
export function formatReduxReport(action: ReduxHistoryEntry): string {
  const timeStr = typeof action.timestamp === 'number' ? formatDateTime(action.timestamp) : action.timestamp;
  const lines: string[] = [
    '🔄 REDUX ACTION REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Action Type: ${action.type || 'UNKNOWN'}`,
    `🕒 Timestamp:   ${timeStr}`,
  ];

  if (action.caller) lines.push(`📍 Caller:      ${action.caller}`);
  if (action.originType) lines.push(`⚙️ Origin:      ${action.originType}`);
  if (action.affectedSlices && action.affectedSlices.length > 0) {
    lines.push(`🍰 Slices:      ${action.affectedSlices.join(', ')}`);
  }

  lines.push('');
  lines.push('📦 Action Payload:');
  lines.push(safeStringify(action.payload));
  lines.push('');

  if (action.prevState !== undefined) {
    lines.push('⏮️ Previous State:');
    lines.push(safeStringify(action.prevState));
    lines.push('');
  }

  if (action.nextState !== undefined) {
    lines.push('⏭️ Next State:');
    lines.push(safeStringify(action.nextState));
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Constructs a formatted report for a Console Log.
 */
export function formatLogReport(log: ConsoleLog): string {
  const timeStr = formatDateTime(log.timestamp);
  const lines: string[] = [
    '📜 CONSOLE LOG REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📌 Level:     ${(log.type || 'info').toUpperCase()}`,
    `🕒 Timestamp: ${timeStr}`,
    `💬 Message:   ${log.message || ''}`,
  ];

  if (log.caller) lines.push(`📍 Caller:    ${log.caller}`);

  lines.push('');

  if (log.rawArgs && log.rawArgs.length > 0) {
    lines.push('📦 Arguments:');
    lines.push(safeStringify(log.rawArgs));
    lines.push('');
  }

  if (log.stack || log.errorStack) {
    lines.push('📜 Stack Trace:');
    lines.push(log.stack || log.errorStack || '');
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

/**
 * Universal Native Share Executor (saves as attached file and opens native share sheet)
 */
async function triggerNativeShare(
  title: string,
  message: string,
  suggestedFilename?: string,
): Promise<void> {
  try {
    const filename = suggestedFilename || `export_${Date.now()}.txt`;
    const fileUri = await writeNativeExportFile(filename, message);
    if (fileUri) {
      const mimeType = filename.endsWith('.json')
        ? 'application/json'
        : filename.endsWith('.log') || filename.endsWith('.txt')
        ? 'text/plain'
        : 'text/plain';
      const shared = await shareNativeFile(fileUri, mimeType, title);
      if (shared) return;
    }
    await Share.share(
      {
        title,
        message,
        url: fileUri || undefined,
      },
      {
        dialogTitle: title,
        subject: title,
      },
    );
  } catch (error: any) {
    if (error?.message !== 'User did not share') {
      Alert.alert('Share Error', error?.message || 'Failed to open share sheet');
    }
  }
}

export async function shareApiReport(log: NetworkLog): Promise<void> {
  const message = formatApiReport(log);
  const filename = `api_${log.id ?? Date.now()}.txt`;
  const title = `API: ${log.method || 'GET'} ${log.url?.substring(0, 40) || ''}`;
  await triggerNativeShare(title, message, filename);
}

export async function sharePushReport(record: PushNotificationRecord): Promise<void> {
  const message = formatPushReport(record);
  const filename = `push_${record.id ?? Date.now()}.txt`;
  const title = `Push: ${record.title || record.id || 'Notification'}`;
  await triggerNativeShare(title, message, filename);
}

export async function shareCrashReport(crash: CrashRecord): Promise<void> {
  const message = formatCrashReport(crash);
  const filename = `crash_${crash.timestamp ?? Date.now()}.txt`;
  const title = `Crash: ${crash.name || crash.message || 'Error'}`;
  await triggerNativeShare(title, message, filename);
}

export async function shareAnalyticsReport(event: AnalyticsEvent): Promise<void> {
  const message = formatAnalyticsReport(event);
  const filename = `analytics_${event.id ?? Date.now()}.txt`;
  const title = `Analytics: ${event.name || 'Event'}`;
  await triggerNativeShare(title, message, filename);
}

export async function shareReduxReport(action: ReduxHistoryEntry): Promise<void> {
  const message = formatReduxReport(action);
  const filename = `redux_${action.id ?? Date.now()}.txt`;
  const title = `Redux: ${action.type || 'Action'}`;
  await triggerNativeShare(title, message, filename);
}

export async function shareLogReport(log: ConsoleLog): Promise<void> {
  const message = formatLogReport(log);
  const filename = `log_${log.id ?? Date.now()}.txt`;
  const title = `Log: ${(log.type || 'info').toUpperCase()} - ${log.message?.substring(0, 30) || ''}`;
  await triggerNativeShare(title, message, filename);
}

/**
 * Constructs a formatted report for a WebSocket / Socket.IO connection.
 */
export function formatSocketReport(record: SocketConnectionRecord): string {
  const clientStr = (record.client || 'websocket').toUpperCase();
  const statusStr = (record.status || 'open').toUpperCase();
  const durationStr = record.duration != null ? `${record.duration}ms` : 'Active / Open';
  const timeStr = formatDateTime(record.startTime || Date.now());

  const lines: string[] = [
    '🔌 WEBSOCKET / SOCKET.IO REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📡 Client:       ${clientStr}`,
    `🌐 URL:          ${record.url || 'N/A'}`,
    `⚡ Status:       ${statusStr}`,
    `⏱️  Connected:    ${timeStr}`,
    `⏳ Duration:     ${durationStr}`,
    `📦 Total Frames: ${record.frames?.length || 0} (${record.sentCount || 0} sent, ${record.receivedCount || 0} recvd)`,
    `📊 Data Size:    ${(record.totalBytesSent || 0) + (record.totalBytesReceived || 0)} bytes`,
  ];

  if (record.protocols) {
    lines.push(`📜 Protocols:    ${Array.isArray(record.protocols) ? record.protocols.join(', ') : record.protocols}`);
  }
  if (record.closeCode != null) {
    lines.push(`🛑 Close Code:   ${record.closeCode} (${record.closeReason || 'N/A'})`);
  }
  if (record.error) {
    lines.push(`❌ Error:        ${record.error}`);
  }
  if (record.caller) {
    lines.push(`📍 Caller:       ${record.caller}`);
  }

  if (record.query && Object.keys(record.query).length > 0) {
    lines.push('');
    lines.push('🔍 Query Parameters:');
    lines.push(safeStringify(record.query));
  }

  if (record.frames && record.frames.length > 0) {
    lines.push('');
    lines.push('💬 Recent Message Frames:');
    record.frames.slice(-10).forEach((f, idx) => {
      const dirIcon = f.direction === 'send' ? '⬆️ SEND' : '⬇️ RECV';
      const eventTag = f.eventName ? ` [${f.eventName}]` : '';
      lines.push(`--- Frame #${idx + 1} (${dirIcon}${eventTag}, ${f.type}, ${f.size || 0}B) ---`);
      lines.push(safeStringify(f.data));
    });
  }

  lines.push('');
  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by React Native InApp Inspector');

  return lines.join('\n');
}

export async function shareSocketReport(record: SocketConnectionRecord): Promise<void> {
  const message = formatSocketReport(record);
  const filename = `socket_${record.id ?? Date.now()}.txt`;
  const title = `Socket: ${record.client?.toUpperCase() || 'WS'} ${record.url?.substring(0, 35) || ''}`;
  await triggerNativeShare(title, message, filename);
}

export type ConsoleLogExportFormat = 'txt' | 'log' | 'json' | 'text' | 'markdown' | 'csv';

export interface ConsoleLogExportOptions {
  includeStackTrace?: boolean;
  includeArguments?: boolean;
  includeCaller?: boolean;
  includeTimestamps?: boolean;
  includeAppInfo?: boolean;
  includeDuplicates?: boolean;
  ignorePattern?: string;
}

export const DEFAULT_CONSOLE_EXPORT_OPTIONS: ConsoleLogExportOptions = {
  includeStackTrace: true,
  includeArguments: true,
  includeCaller: true,
  includeTimestamps: true,
  includeAppInfo: true,
  includeDuplicates: false,
  ignorePattern: '',
};

/**
 * Generates filename in format: log_DDMMYY_random6digittext.txt or .log
 */
export function generateConsoleLogsFilename(
  format: ConsoleLogExportFormat = 'txt',
): string {
  const now = new Date();
  const dd = String(now.getDate()).padStart(2, '0');
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const yy = String(now.getFullYear()).slice(-2);
  const random6 = Math.random().toString(36).substring(2, 8).padEnd(6, '0');
  const ext = format === 'log' ? 'log' : 'txt';
  return `log_${dd}${mm}${yy}_${random6}.${ext}`;
}

/**
 * Formats a list of console logs for export with clean structured separators and customizable options.
 */
export function formatConsoleLogsExport(
  logs: ConsoleLog[],
  format: ConsoleLogExportFormat = 'txt',
  options: ConsoleLogExportOptions = DEFAULT_CONSOLE_EXPORT_OPTIONS,
): string {
  if (!logs || logs.length === 0) {
    return 'No console logs to export.';
  }

  const {
    includeStackTrace = true,
    includeArguments = true,
    includeCaller = true,
    includeTimestamps = true,
    includeAppInfo = true,
    includeDuplicates = false,
    ignorePattern = '',
  } = options;

  let activeLogs = logs;
  if (ignorePattern && ignorePattern.trim().length > 0) {
    try {
      const reg = new RegExp(ignorePattern.trim(), 'i');
      activeLogs = logs.filter(l => {
        const msg = l.message || '';
        const argsStr = l.rawArgs ? safeStringify(l.rawArgs) : '';
        const callerStr = l.caller || '';
        return !reg.test(msg) && !reg.test(argsStr) && !reg.test(callerStr);
      });
    } catch {
      // Keep logs as is if pattern is invalid
    }
  }

  if (activeLogs.length === 0) {
    return 'No console logs to export (all filtered out).';
  }

  const now = new Date();
  const timeHeader = now.toLocaleString();
  const sepLine = '********************************************************************************';

  const headerLines: string[] = [];
  if (includeAppInfo) {
    headerLines.push(
      `/${sepLine}`,
      ` * 📜 CONSOLE LOGS EXPORT (${format.toUpperCase()})`,
      ` * 🕒 Exported At: ${timeHeader}`,
      ` * 📊 Total Logs:   ${logs.length}`,
      ` * ⚙️ Generator:   React Native InApp Inspector`,
      ` ${sepLine}/`,
      '',
    );
  }

  const body = logs
    .map((l, index) => {
      const logNum = index + 1;
      const dt = formatDateTime(l.timestamp);
      const lvl = (l.type || 'info').toUpperCase();
      const dup =
        includeDuplicates && l.duplicateCount && l.duplicateCount > 1
          ? ` [DUPLICATES: ×${l.duplicateCount}]`
          : '';

      const lines: string[] = [
        `/${sepLine}`,
        ` * 📌 LOG #${logNum} Starts [${lvl}]${includeTimestamps ? ` - ${dt}` : ''}${dup}`,
        ` ${sepLine}/`,
      ];

      if (includeCaller && l.caller) {
        lines.push(`📍 Caller:    ${l.caller}`);
      }
      if (includeTimestamps) {
        lines.push(`🕒 Time:      ${dt}`);
      }
      lines.push(`🏷️ Level:     ${lvl}`);
      if (l.sourceMethod && l.sourceMethod !== l.type) {
        lines.push(`⚙️ Method:    console.${l.sourceMethod}()`);
      }

      lines.push('');
      lines.push('💬 Message:');
      lines.push(l.message || '(Empty message)');

      if (includeArguments && l.rawArgs && l.rawArgs.length > 0) {
        lines.push('');
        lines.push('📦 Arguments / Data:');
        lines.push(safeStringify(l.rawArgs));
      }

      if (includeStackTrace && (l.stack || l.errorStack)) {
        lines.push('');
        lines.push('📜 Stack Trace & Frames:');
        const cleanStack = (l.stack || l.errorStack || '')
          .split('\n')
          .map(line => `  ${line}`)
          .join('\n');
        lines.push(cleanStack);
      }

      lines.push('');
      lines.push(`/${sepLine}`);
      lines.push(` * 🏁 LOG #${logNum} Ends`);
      lines.push(` ${sepLine}/`);

      return lines.join('\n');
    })
    .join('\n\n');

  const footer = includeAppInfo
    ? [
        '',
        `/${sepLine}`,
        ' * 🏁 END OF CONSOLE LOGS EXPORT',
        ` ${sepLine}/`,
      ].join('\n')
    : '';

  return `${headerLines.join('\n')}${body}${footer}`;
}

/**
 * Rapid byte size estimator for selected logs and export format before full string export.
 */
export function estimateConsoleLogsExportSize(
  logs: ConsoleLog[],
  format: ConsoleLogExportFormat = 'txt',
  options: ConsoleLogExportOptions = DEFAULT_CONSOLE_EXPORT_OPTIONS,
): number {
  if (!logs || logs.length === 0) return 0;
  const sampleCount = Math.min(logs.length, 20);
  const sampleLogs = logs.slice(0, sampleCount);
  const sampleOutput = formatConsoleLogsExport(sampleLogs, format, options);
  const avgBytesPerLog = sampleOutput.length / sampleCount;
  return Math.round(avgBytesPerLog * logs.length);
}

/**
 * Triggers native share sheet for exported console logs.
 */
export async function shareConsoleLogs(
  logs: ConsoleLog[],
  format: ConsoleLogExportFormat = 'txt',
  options: ConsoleLogExportOptions = DEFAULT_CONSOLE_EXPORT_OPTIONS,
  customTitle?: string,
): Promise<void> {
  const content = formatConsoleLogsExport(logs, format, options);
  const filename = generateConsoleLogsFilename(format);
  const title = customTitle || filename;
  await triggerNativeShare(title, content, filename);
}

export type NetworkLogExportFormat = 'txt' | 'log' | 'json' | 'curl';

export interface NetworkLogExportOptions {
  includeRequestHeaders?: boolean;
  includeRequestBody?: boolean;
  includeResponseHeaders?: boolean;
  includeResponseBody?: boolean;
  includeCurlCommand?: boolean;
  includeTimestamps?: boolean;
  includeAppInfo?: boolean;
  ignorePattern?: string;
}

export const DEFAULT_NETWORK_EXPORT_OPTIONS: NetworkLogExportOptions = {
  includeRequestHeaders: true,
  includeRequestBody: true,
  includeResponseHeaders: true,
  includeResponseBody: true,
  includeCurlCommand: true,
  includeTimestamps: true,
  includeAppInfo: true,
  ignorePattern: '',
};

/**
 * Generates filename in format: api_DDMMYY_random6digittext.txt / .log / .json / .sh
 */
export function generateNetworkLogsFilename(
  format: NetworkLogExportFormat = 'txt',
): string {
  const now = new Date();
  const dd = String(now.getDate()).padStart(2, '0');
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const yy = String(now.getFullYear()).slice(-2);
  const random6 = Math.random().toString(36).substring(2, 8).padEnd(6, '0');
  const ext = format === 'log' ? 'log' : 'txt';
  return `api_${dd}${mm}${yy}_${random6}.${ext}`;
}

/**
 * Formats a list of network API logs for export with clean structured separators and customizable options.
 */
export function formatNetworkLogsExport(
  logs: NetworkLog[],
  format: NetworkLogExportFormat = 'txt',
  options: NetworkLogExportOptions = DEFAULT_NETWORK_EXPORT_OPTIONS,
): string {
  if (!logs || logs.length === 0) {
    return 'No API requests to export.';
  }

  const {
    includeRequestHeaders = true,
    includeRequestBody = true,
    includeResponseHeaders = true,
    includeResponseBody = true,
    includeCurlCommand = true,
    includeTimestamps = true,
    includeAppInfo = true,
    ignorePattern = '',
  } = options;

  let activeLogs = logs;
  if (ignorePattern && ignorePattern.trim().length > 0) {
    try {
      const reg = new RegExp(ignorePattern.trim(), 'i');
      activeLogs = logs.filter(l => {
        const url = l.url || '';
        const method = l.method || '';
        const client = l.client || '';
        const reqStr = l.request ? safeStringify(l.request) : '';
        const resStr = l.response ? safeStringify(l.response) : '';
        const reqHeadersStr = l.requestHeaders ? safeStringify(l.requestHeaders) : '';
        const resHeadersStr = l.responseHeaders ? safeStringify(l.responseHeaders) : '';
        return (
          !reg.test(url) &&
          !reg.test(method) &&
          !reg.test(client) &&
          !reg.test(reqStr) &&
          !reg.test(resStr) &&
          !reg.test(reqHeadersStr) &&
          !reg.test(resHeadersStr)
        );
      });
    } catch {
      // Keep logs as is if pattern is invalid
    }
  }

  if (activeLogs.length === 0) {
    return 'No API requests to export (all filtered out).';
  }

  const now = new Date();
  const timeHeader = now.toLocaleString();
  const sepLine = '********************************************************************************';

  if (format === 'json') {
    const serialized = activeLogs.map((l, index) => {
      const item: any = {
        index: index + 1,
        id: l.id,
        url: l.url,
        method: (l.method || 'GET').toUpperCase(),
        status: l.status,
        duration: l.duration,
        startTime: l.startTime,
        client: l.client,
      };
      if (includeRequestHeaders && l.requestHeaders) {
        item.requestHeaders = l.requestHeaders;
      }
      if (includeRequestBody && l.request != null) {
        item.request = l.request;
      }
      if (includeResponseHeaders && l.responseHeaders) {
        item.responseHeaders = l.responseHeaders;
      }
      if (includeResponseBody && l.response != null) {
        item.response = l.response;
      }
      if (includeCurlCommand) {
        item.curl = getCurlCommand(l);
      }
      return item;
    });
    return JSON.stringify(serialized, null, 2);
  }

  if (format === 'curl') {
    const lines: string[] = [
      '#!/usr/bin/env bash',
      '# ============================================================================== ',
      '# 🚀 API Network Logs - cURL Script Export',
      `# 🕒 Exported At:     ${timeHeader}`,
      `# 📊 Total Commands:  ${activeLogs.length}`,
      '# ⚙️ Generator:       React Native InApp Inspector',
      '# ==============================================================================\n',
    ];

    activeLogs.forEach((l, index) => {
      const reqNum = index + 1;
      const method = (l.method || 'GET').toUpperCase();
      const statusStr =
        l.status === 0
          ? 'Failed / Error'
          : l.status != null
          ? String(l.status)
          : 'Pending';
      const durationStr = l.duration != null ? `${l.duration}ms` : 'N/A';
      const dt = formatDateTime(l.startTime || Date.now());

      lines.push(
        `# Request #${reqNum}: [${method}] ${l.url || 'N/A'} (Status: ${statusStr}, ${durationStr}, ${dt})`,
      );
      const curl = getCurlCommand(l);
      if (curl) {
        lines.push(curl);
      } else {
        lines.push(`curl -X ${method} "${l.url || ''}"`);
      }
      lines.push('');
    });

    return lines.join('\n');
  }

  // format === 'txt' or 'log'
  const headerLines: string[] = [];
  if (includeAppInfo) {
    headerLines.push(
      `/${sepLine}`,
      ` * 🚀 API NETWORK LOGS EXPORT (${format.toUpperCase()})`,
      ` * 🕒 Exported At:    ${timeHeader}`,
      ` * 📊 Total Requests: ${activeLogs.length}`,
      ` * ⚙️ Generator:      React Native InApp Inspector`,
      ` ${sepLine}/`,
      '',
    );
  }

  const body = activeLogs
    .map((l, index) => {
      const reqNum = index + 1;
      const dt = formatDateTime(l.startTime || Date.now());
      const method = (l.method || 'GET').toUpperCase();
      const statusStr =
        l.status === 0
          ? 'Failed / Network Error'
          : l.status != null
          ? `${l.status} ${l.status === 200 ? 'OK' : ''}`.trim()
          : 'Pending';
      const durationStr = l.duration != null ? `${l.duration}ms` : 'N/A';

      const lines: string[] = [
        `/${sepLine}`,
        ` * 📌 REQUEST #${reqNum} Starts [${method}] [${statusStr}] [${durationStr}]${
          includeTimestamps ? ` - ${dt}` : ''
        }`,
        ` ${sepLine}/`,
      ];

      lines.push(`🌐 URL:        ${l.url || 'N/A'}`);
      lines.push(`📌 Method:     ${method}`);
      lines.push(`📊 Status:     ${statusStr}`);
      lines.push(`⏱️ Duration:   ${durationStr}`);
      if (includeTimestamps) {
        lines.push(`🕒 Time:       ${dt}`);
      }
      if (l.client) {
        lines.push(`🔌 Client:     ${l.client.toUpperCase()}`);
      }

      if (
        includeRequestHeaders &&
        l.requestHeaders &&
        Object.keys(l.requestHeaders).length > 0
      ) {
        lines.push('');
        lines.push('📋 Request Headers:');
        lines.push(safeStringify(l.requestHeaders));
      }

      if (includeRequestBody && l.request != null && l.request !== '') {
        lines.push('');
        lines.push('📝 Request Body:');
        lines.push(safeStringify(l.request));
      }

      if (
        includeResponseHeaders &&
        l.responseHeaders &&
        Object.keys(l.responseHeaders).length > 0
      ) {
        lines.push('');
        lines.push('📑 Response Headers:');
        lines.push(safeStringify(l.responseHeaders));
      }

      if (includeResponseBody && l.response != null && l.response !== '') {
        lines.push('');
        lines.push('📥 Response Data:');
        lines.push(safeStringify(l.response));
      }

      if (includeCurlCommand) {
        const curlCmd = getCurlCommand(l);
        if (curlCmd) {
          lines.push('');
          lines.push('💻 cURL Command:');
          lines.push(curlCmd);
        }
      }

      lines.push('');
      lines.push(`/${sepLine}`);
      lines.push(` * 🏁 REQUEST #${reqNum} Ends`);
      lines.push(` ${sepLine}/`);

      return lines.join('\n');
    })
    .join('\n\n');

  const footer = includeAppInfo
    ? [
        '',
        `/${sepLine}`,
        ' * 🏁 END OF API NETWORK LOGS EXPORT',
        ` ${sepLine}/`,
      ].join('\n')
    : '';

  return `${headerLines.join('\n')}${body}${footer}`;
}

/**
 * Rapid byte size estimator for selected network logs and export format before full string export.
 */
export function estimateNetworkLogsExportSize(
  logs: NetworkLog[],
  format: NetworkLogExportFormat = 'txt',
  options: NetworkLogExportOptions = DEFAULT_NETWORK_EXPORT_OPTIONS,
): number {
  if (!logs || logs.length === 0) return 0;
  const sampleCount = Math.min(logs.length, 10);
  const sampleLogs = logs.slice(0, sampleCount);
  const sampleOutput = formatNetworkLogsExport(sampleLogs, format, options);
  const avgBytesPerLog = sampleOutput.length / sampleCount;
  return Math.round(avgBytesPerLog * logs.length);
}

/**
 * Triggers native share sheet for exported network logs.
 */
export async function shareNetworkLogs(
  logs: NetworkLog[],
  format: NetworkLogExportFormat = 'txt',
  options: NetworkLogExportOptions = DEFAULT_NETWORK_EXPORT_OPTIONS,
  customTitle?: string,
): Promise<void> {
  const content = formatNetworkLogsExport(logs, format, options);
  const filename = generateNetworkLogsFilename(format);
  const title = customTitle || filename;
  await triggerNativeShare(title, content, filename);
}

