import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 110, // Room for static footer action bar
    gap: 14,
  },
  headerHero: {
    marginTop: 4,
    marginBottom: 4,
    alignItems: 'center',
  },
  headerBadgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3E8FF',
    borderColor: '#D8B4FE',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 8,
  },
  headerBadge: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#5C2D91',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 18,
    maxWidth: 320,
  },

  // ─── Playground Top Nav Tabs ────────────────────────────────────────────────
  tabBarContainer: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 4,
  },
  tabItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#E2E8F0',
    gap: 5,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  tabItemActive: {
    backgroundColor: '#5C2D91',
    borderColor: '#5C2D91',
    ...Platform.select({
      ios: {
        shadowColor: '#5C2D91',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.22,
        shadowRadius: 6,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  tabText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#64748B',
  },
  tabTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },

  // ─── Graphics & Activity Graph Card ─────────────────────────────────────────
  statsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  liveIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16A34A',
  },
  liveText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#16A34A',
    letterSpacing: 0.5,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  statBox: {
    flex: 1,
    minWidth: 0,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  statVal: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  statLbl: {
    fontSize: 9,
    color: '#64748B',
    marginTop: 2,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    textAlign: 'center',
  },

  // ─── Panel Cards ────────────────────────────────────────────────────────────
  panelCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  panelHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  panelHeader: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    flexShrink: 1,
  },
  panelHeaderBadge: {
    fontSize: 9,
    fontWeight: '700',
    color: '#64748B',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  btnRow: {
    flexDirection: 'row',
    gap: 8,
  },
  gridBtn: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1.2,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 8,
    backgroundColor: '#FFFFFF',
  },
  btnText: {
    fontSize: 11.5,
    fontWeight: '700',
    textAlign: 'center',
    flexShrink: 1,
  },
  fullWidthBtn: {
    width: '100%',
    minHeight: 42,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 9,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  fullWidthBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
    textAlign: 'center',
    flexShrink: 1,
  },

  // ─── Static Footer Action Bar ───────────────────────────────────────────────
  staticFooterContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 26 : 14,
    gap: 6,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.06,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  footerButton: {
    width: '100%',
    minHeight: 46,
    borderRadius: 13,
    backgroundColor: '#5C2D91',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 8,
    ...Platform.select({
      ios: {
        shadowColor: '#5C2D91',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  footerButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },

  // ─── Info & Code Snippet Rows ───────────────────────────────────────────────
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 8,
  },
  infoLabel: {
    fontSize: 11.5,
    color: '#64748B',
    fontWeight: '600',
    flexShrink: 1,
  },
  infoValue: {
    fontSize: 11.5,
    color: '#0F172A',
    fontWeight: '700',
    textAlign: 'right',
    flexShrink: 1,
  },
  codeSnippet: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  codeText: {
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 11.5,
    color: '#38BDF8',
    fontWeight: '600',
    flexShrink: 1,
  },

  // ─── Details Screen Buttons ─────────────────────────────────────────────────
  detailsLogBtn: {
    backgroundColor: '#059669',
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    gap: 8,
  },
  detailsBackBtn: {
    backgroundColor: '#475569',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    gap: 8,
  },

  // ─── Reusable Layout & Typography Utilities ─────────────────────────────────
  flexShrink1: { flexShrink: 1 },
  rowAlignCenterGap6: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  rowAlignCenterGap4: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  rowBetweenCenter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  gap6: { gap: 6 },
  gap8: { gap: 8 },
  gap2Mt4: { gap: 2, marginTop: 4 },
  gap8Mt4: { gap: 8, marginTop: 4 },
  mt4: { marginTop: 4 },
  headerBadgeText: { marginLeft: 4 },

  // ─── Live Activity Telemetry Card Styles ───────────────────────────────────
  telemetryBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingTop: 8,
    paddingBottom: 4,
    paddingHorizontal: 8,
    overflow: 'hidden',
  },
  telemetryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  telemetryTextLeft: { fontSize: 10, fontWeight: '700', color: '#64748B' },
  telemetryTextIndigo: { color: '#4F46E5' },
  telemetryTextGreen: { fontSize: 10, fontWeight: '700', color: '#16A34A' },
  telemetryAxisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 2,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  telemetryAxisLabel: { fontSize: 9, color: '#94A3B8', fontWeight: '700' },
  telemetryAxisLabelNow: { fontSize: 9, color: '#4F46E5', fontWeight: '800' },
  eventBreakdownTitle: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#0F172A',
    textTransform: 'uppercase',
  },
  eventBreakdownSubtitle: { fontSize: 10, color: '#64748B', fontWeight: '600' },
  distributionBar: {
    flexDirection: 'row',
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: '#E2E8F0',
  },
  barApi: { backgroundColor: '#4F46E5' },
  barLog: { backgroundColor: '#F59E0B' },
  barAnalytics: { backgroundColor: '#0D9488' },
  barEmpty: { flex: 1, backgroundColor: '#CBD5E1' },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  legendDotApi: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#4F46E5' },
  legendTextApi: { fontSize: 10, fontWeight: '700', color: '#4F46E5' },
  legendDotLog: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#F59E0B' },
  legendTextLog: { fontSize: 10, fontWeight: '700', color: '#D97706' },
  legendDotAnalytics: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#0D9488' },
  legendTextAnalytics: { fontSize: 10, fontWeight: '700', color: '#0D9488' },
  legendDotStore: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#7C3AED' },
  legendTextStore: { fontSize: 10, fontWeight: '700', color: '#7C3AED' },
  textApiColor: { color: '#4F46E5' },
  textLogColor: { color: '#D97706' },
  textAnalyticsColor: { color: '#0D9488' },
  textStoreColor: { color: '#7C3AED' },

  // ─── Card Variations & Badges ───────────────────────────────────────────────
  panelCardCrash: { borderColor: '#FECDD3' },
  panelHeaderCrash: { color: '#E11D48' },
  panelHeaderBadgeCrash: { backgroundColor: '#FFE4E6', color: '#BE123C' },
  panelHeaderBadgeNpm: { backgroundColor: '#DCFCE7', color: '#16A34A', fontWeight: '800' },
  panelHeaderBadgeGithub: { backgroundColor: '#F3E8FF', color: '#5C2D91', fontWeight: '800' },
  metricsStrip: { flexDirection: 'row', gap: 8, marginTop: 2 },
  statBoxPv8: { paddingVertical: 8 },
  statValPurple: { color: '#5C2D91', fontSize: 14 },
  statValGreen: { color: '#16A34A', fontSize: 14 },
  statValBlue: { color: '#0284C7', fontSize: 14 },
  statValDark: { color: '#0F172A', fontSize: 14 },
  statValRed: { color: '#DC2626', fontSize: 14 },
  infoValuePurple: { color: '#5C2D91' },
  infoValueGreen: { color: '#16A34A' },
  infoValueAmber: { color: '#D97706' },
  infoValueIndigo: { color: '#6366F1' },
  featureBulletText: { fontSize: 12, color: '#334155', lineHeight: 18 },
  featureBulletBold: { fontWeight: '700' },
});
