import { StyleSheet, Platform } from 'react-native';

const INTER_FONT = Platform.select({
  ios: 'Inter',
  android: 'Inter',
  default: 'Inter, -apple-system, system-ui, Roboto, sans-serif',
});

export const styles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 110, // Room for static footer action bar
    gap: 14,
  },
  headerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 14,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  headerBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerBrandLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    flex: 1,
  },
  headerLogoBox: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    ...Platform.select({
      ios: {
        shadowColor: '#38BDF8',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  headerBrandTextCol: {
    flex: 1,
    gap: 1,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
    fontFamily: INTER_FONT,
  },
  headerSubtitle: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#64748B',
    letterSpacing: -0.1,
    fontFamily: INTER_FONT,
  },
  headerDescription: {
    fontSize: 11.5,
    color: '#475569',
    lineHeight: 16.5,
    letterSpacing: -0.1,
    fontFamily: INTER_FONT,
  },
  headerRefreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF2FF',
    borderColor: '#C7D2FE',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 9,
    paddingVertical: 4.5,
    gap: 4.5,
    ...Platform.select({
      ios: {
        shadowColor: '#4F46E5',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
      },
      android: {
        elevation: 1.5,
      },
    }),
  },
  headerRefreshBtnText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#4F46E5',
    letterSpacing: 0.2,
    fontFamily: INTER_FONT,
  },
  headerLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    gap: 5,
  },
  headerLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10B981',
  },
  headerLiveText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#047857',
    letterSpacing: 0.4,
    fontFamily: INTER_FONT,
  },
  headerLinksRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerNpmLinkCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF1F2',
    borderColor: '#FECDD3',
    borderWidth: 1.2,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 8.5,
    ...Platform.select({
      ios: {
        shadowColor: '#E11D48',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 5,
      },
      android: {
        elevation: 1.5,
      },
    }),
  },
  headerNpmLinkLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  headerNpmIconBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#FFE4E6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerNpmInfoCol: {
    gap: 1.5,
  },
  headerNpmName: {
    fontSize: 12.5,
    fontWeight: '900',
    color: '#9F1239',
    letterSpacing: -0.2,
  },
  headerNpmVersionPill: {
    backgroundColor: '#E11D48',
    borderRadius: 5,
    paddingHorizontal: 4.5,
    paddingVertical: 1,
  },
  headerNpmVersionPillText: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  headerNpmSubText: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#BE123C',
  },
  headerLinkArrowBadgeNpm: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFE4E6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerGithubLinkCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderWidth: 1.2,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 8.5,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 5,
      },
      android: {
        elevation: 1.5,
      },
    }),
  },
  headerGithubLinkLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  headerGithubIconBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerGithubInfoCol: {
    gap: 1.5,
  },
  headerGithubName: {
    fontSize: 12.5,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  headerGithubStarBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF9C3',
    borderColor: '#FEF08A',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 4,
    paddingVertical: 1,
    gap: 2.5,
  },
  headerGithubStarCount: {
    fontSize: 9,
    fontWeight: '800',
    color: '#854D0E',
  },
  headerGithubSubText: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#64748B',
  },
  headerLinkArrowBadgeGh: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerInstallBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0F172A',
    borderRadius: 12,
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#1E293B',
    gap: 8,
  },
  headerInstallLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  headerInstallPrompt: {
    fontSize: 12,
    fontWeight: '800',
    color: '#38BDF8',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  headerInstallCode: {
    flex: 1,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 11.5,
    color: '#F1F5F9',
    fontWeight: '600',
  },
  headerInstallCopyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    borderColor: '#334155',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4.5,
    gap: 4.5,
  },
  headerInstallCopyBtnSuccess: {
    backgroundColor: '#059669',
    borderColor: '#10B981',
  },
  headerInstallCopyText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  headerFeaturesToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  headerFeaturesToggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  headerFeaturesToggleTitle: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#1E293B',
    letterSpacing: -0.1,
    fontFamily: INTER_FONT,
  },
  headerFeaturesToggleAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerFeaturesToggleActionText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#4F46E5',
    letterSpacing: 0.1,
    fontFamily: INTER_FONT,
  },
  headerFeatureCardsContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 8,
  },
  headerFeatureCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 11,
    padding: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    gap: 10,
  },
  headerFeatureIconBox: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 1,
  },
  headerFeatureContent: {
    flex: 1,
    gap: 2,
  },
  headerFeatureTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.15,
    lineHeight: 16,
    fontFamily: INTER_FONT,
  },
  headerFeatureDesc: {
    fontSize: 11,
    color: '#64748B',
    lineHeight: 16,
    letterSpacing: -0.05,
    fontFamily: INTER_FONT,
  },
  headerRepoDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  headerRepoDetailItem: {
    flex: 1,
    alignItems: 'center',
    gap: 2.5,
  },
  headerRepoDetailLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    fontFamily: INTER_FONT,
  },
  headerRepoDetailValue: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
    lineHeight: 16,
    fontFamily: INTER_FONT,
  },
  headerRepoDetailDivider: {
    width: 1,
    height: 20,
    backgroundColor: '#E2E8F0',
  },

  // ─── Playground Top Nav Tabs ────────────────────────────────────────────────
  tabBarContainer: {
    marginBottom: 6,
  },
  tabBarScroll: {
    gap: 8,
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#E2E8F0',
    gap: 6,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  tabItemActive: {
    backgroundColor: '#5C2D91',
    borderColor: '#5C2D91',
    ...Platform.select({
      ios: {
        shadowColor: '#5C2D91',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.22,
        shadowRadius: 6,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  tabText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#64748B',
  },
  tabTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  tabBadge: {
    paddingHorizontal: 5.5,
    paddingVertical: 1.5,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    marginLeft: 1,
  },
  tabBadgeActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
  },
  tabBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748B',
  },
  tabBadgeTextActive: {
    color: '#FFFFFF',
  },

  // ─── Collapsible Accordion Card Styles ───────────────────────────────────────
  accordionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  accordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  accordionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    flexShrink: 1,
  },
  accordionHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  accordionTitle: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
    fontFamily: INTER_FONT,
    flexShrink: 1,
  },
  accordionChevronBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  accordionContent: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    gap: 12,
  },

  // ─── NPM Package Insights Styles ───────────────────────────────────────────
  insightsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 14,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  insightsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  insightsHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  insightsHeaderTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  insightsLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: 1,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  insightsLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10B981',
  },
  insightsLiveText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#059669',
    letterSpacing: 0.4,
  },
  insightsHeroStats: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 8,
  },
  insightsHeroItem: {
    flex: 1,
    gap: 2,
  },
  insightsHeroLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  insightsHeroValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  insightsHeroValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.5,
  },
  insightsHeroBadge: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#059669',
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
  },
  insightsHeroDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#E2E8F0',
  },
  headerTabContainer: {
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    padding: 3,
    gap: 3,
  },
  headerTabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 7,
    paddingHorizontal: 4,
    borderRadius: 7.5,
    gap: 4,
  },
  headerTabBtnActive: {
    backgroundColor: '#FFFFFF',
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 1.5 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
      },
      android: {
        elevation: 1.5,
      },
    }),
  },
  headerTabText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#64748B',
    fontFamily: INTER_FONT,
  },
  headerTabTextActive: {
    color: '#0F172A',
    fontWeight: '800',
  },
  insightsChartBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 8,
  },
  insightsChartTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  insightsChartTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  insightsChartTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  insightsChartSub: {
    fontSize: 10,
    fontWeight: '700',
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  insightsDayAxisRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 4,
    gap: 2,
  },
  insightsDayPill: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  insightsDayPillActive: {
    backgroundColor: '#EEF2FF',
  },
  insightsPlatformPillActive: {
    borderWidth: 1,
  },
  insightsDayPillText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#94A3B8',
    textAlign: 'center',
  },
  insightsDayPillTextActive: {
    color: '#4F46E5',
    fontWeight: '800',
  },
  insightsPlatformPillTextActive: {
    fontWeight: '800',
  },
  insightsAxisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  insightsAxisLabel: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontWeight: '600',
  },
  insightsCardsContainer: {
    gap: 10,
  },
  insightsSubCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 6,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  countryDonutSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginVertical: 10,
  },
  countryDonutWrapper: {
    width: 130,
    height: 130,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  countryDonutCenterContent: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countryDonutCenterVal: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F172A',
    fontFamily: INTER_FONT,
    letterSpacing: -0.3,
  },
  countryDonutCenterLbl: {
    fontSize: 8,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  countryDonutLegendCol: {
    flex: 1,
    gap: 4.5,
  },
  countryDonutLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 7,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  countryDonutLegendLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flex: 1,
  },
  countryDonutLegendDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  countryDonutLegendName: {
    fontSize: 10,
    fontWeight: '700',
    color: '#334155',
    fontFamily: INTER_FONT,
  },
  countryDonutLegendVal: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  countrySpectrumContainer: {
    height: 12,
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    overflow: 'hidden',
    marginTop: 6,
    marginBottom: 10,
    gap: 2,
  },
  countrySpectrumSegment: {
    height: '100%',
    borderRadius: 2,
  },
  countryLegendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  countryLegendChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    gap: 4,
  },
  countrySpectrumDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  countrySpectrumText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#334155',
    fontFamily: INTER_FONT,
  },
  countryLegendPct: {
    fontSize: 9,
    fontWeight: '800',
    color: '#0F172A',
  },
  countryRankCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FAFAFC',
    borderColor: '#F1F5F9',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  countryRankCardActive: {
    backgroundColor: '#F5F3FF',
    borderColor: '#DDD6FE',
  },
  countryRankLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    flex: 1,
    paddingRight: 10,
  },
  countryRankNum: {
    fontSize: 11,
    fontWeight: '900',
    color: '#94A3B8',
    minWidth: 18,
  },
  countryRankNumTop: {
    color: '#4F46E5',
  },
  countryListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  countryListLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    paddingRight: 10,
  },
  countryListFlag: {
    fontSize: 16,
  },
  countryCodePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3.5,
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 5.5,
    paddingVertical: 2.5,
    borderRadius: 5,
    minWidth: 42,
    justifyContent: 'center',
  },
  countryCodePillText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#334155',
    fontFamily: INTER_FONT,
  },
  countryListNameCol: {
    flex: 1,
    gap: 4,
    justifyContent: 'center',
  },
  countryListNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'nowrap',
  },
  countryListName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1E293B',
    fontFamily: INTER_FONT,
  },
  detectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 1.5,
  },
  detectedBadgeText: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#059669',
  },
  countryProgressBarBg: {
    height: 5,
    backgroundColor: '#E2E8F0',
    borderRadius: 2.5,
    width: '100%',
    overflow: 'hidden',
  },
  countryProgressBarFill: {
    height: '100%',
    borderRadius: 2.5,
  },
  countryListRight: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 1,
    minWidth: 64,
  },
  countryListDownloads: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: INTER_FONT,
  },
  countryListPct: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#64748B',
  },
  ingestDeltaBadge: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    marginTop: 2,
  },
  ingestDeltaText: {
    fontSize: 7.5,
    fontWeight: '800',
  },
  ingestStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FAF5FF',
    borderColor: '#F3E8FF',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 10,
  },
  ingestStatItem: {
    alignItems: 'center',
    gap: 2,
    flex: 1,
  },
  ingestStatVal: {
    fontSize: 11,
    fontWeight: '900',
    color: '#6B21A8',
    fontFamily: INTER_FONT,
  },
  ingestStatLbl: {
    fontSize: 8,
    fontWeight: '700',
    color: '#9333EA',
    letterSpacing: 0.2,
    textTransform: 'uppercase',
  },
  insightsCardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  insightsCardTitleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  insightsCardTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  insightsCardBadge: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  insightsCardLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    gap: 4,
  },
  insightsCardLiveDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#16A34A',
  },
  insightsCardLiveText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#16A34A',
  },
  insightsLatestEventBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  insightsLatestEventLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  insightsLatestEventText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#334155',
  },
  insightsLatestEventTime: {
    fontSize: 9,
    fontWeight: '600',
    color: '#94A3B8',
  },
  insightsSectionBlock: {
    gap: 8,
  },
  insightsSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F172A',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  insightsProgressBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E2E8F0',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  insightsPlatformsGrid: {
    flexDirection: 'row',
    gap: 6,
  },
  platformPillsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  insightsPlatformPill: {
    minWidth: '47%',
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  insightsPlatformLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  insightsPlatformDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  insightsPlatformName: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#334155',
  },
  insightsPlatformPct: {
    fontSize: 10.5,
    fontWeight: '900',
    color: '#0F172A',
  },
  platformDynamicRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 6,
    gap: 4,
  },
  platformDynamicPill: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4.5,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  platformDynamicPillText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#475569',
    fontFamily: INTER_FONT,
    textAlign: 'center',
  },
  platformGraphSection: {
    gap: 9,
    marginTop: 6,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  platformGraphSectionTitle: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 0.4,
    fontFamily: INTER_FONT,
    textTransform: 'uppercase',
  },
  platformMetricRow: {
    gap: 4,
  },
  platformMetricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  platformMetricLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
    fontFamily: INTER_FONT,
  },
  platformMetricValues: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: INTER_FONT,
  },
  platformDualBar: {
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#E2E8F0',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  insightsReleasesList: {
    gap: 6,
  },
  insightsReleaseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  insightsReleaseLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  insightsReleaseBadge: {
    backgroundColor: '#EEF2FF',
    borderColor: '#C7D2FE',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  insightsReleaseVersion: {
    fontSize: 11,
    fontWeight: '800',
    color: '#4F46E5',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  insightsReleaseDate: {
    fontSize: 10.5,
    color: '#64748B',
    fontWeight: '600',
    fontFamily: INTER_FONT,
  },
  insightsReleaseRight: {
    alignItems: 'flex-end',
    gap: 1.5,
  },
  insightsReleaseSize: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.1,
    fontFamily: INTER_FONT,
  },
  insightsReleaseFiles: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontWeight: '600',
    fontFamily: INTER_FONT,
  },
  insightsContributorsList: {
    flexDirection: 'row',
    gap: 8,
  },
  insightsContributorCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 9,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 8,
  },
  insightsContributorAvatarBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  insightsContributorAvatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  insightsContributorInfo: {
    flex: 1,
    gap: 1,
  },
  insightsContributorName: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F172A',
  },
  insightsContributorCommits: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#059669',
  },
  insightsSpecsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  insightsSpecBox: {
    flex: 1,
    minWidth: '46%',
    backgroundColor: '#F8FAFC',
    borderRadius: 11,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 3,
  },
  insightsSpecLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    fontFamily: INTER_FONT,
  },
  insightsSpecVal: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
    lineHeight: 16,
    fontFamily: INTER_FONT,
  },
  insightsHostCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0FDF4',
    borderColor: '#BBF7D0',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 8,
  },
  insightsHostLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    flex: 1,
  },
  insightsHostIcon: {
    fontSize: 18,
  },
  insightsHostTextCol: {
    flex: 1,
    gap: 1.5,
  },
  insightsHostTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#166534',
  },
  insightsHostSub: {
    fontSize: 10,
    color: '#15803D',
    fontWeight: '600',
  },
  insightsHostBadge: {
    backgroundColor: '#16A34A',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2.5,
  },
  insightsHostBadgeText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.4,
  },
  insightsRefreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    gap: 6,
    marginTop: 2,
  },
  insightsRefreshText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4F46E5',
  },

  // ─── Country Download Distribution Styles ───────────────────────────────────
  countryStackedContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 8,
    marginBottom: 8,
  },
  countryStackedBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E2E8F0',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  countryStackedLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  countryLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  countryLegendDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  countryLegendText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748B',
    fontFamily: INTER_FONT,
  },
  countryList: {
    gap: 8,
  },
  countryRow: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 6,
  },
  countryRowHost: {
    backgroundColor: '#F0FDF4',
    borderColor: '#BBF7D0',
  },
  countryTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  countryLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  countryRankBadge: {
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderWidth: 1,
  },
  countryRankText: {
    fontSize: 9,
    fontWeight: '800',
    fontFamily: INTER_FONT,
  },
  countryFlag: {
    fontSize: 15,
  },
  countryName: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.1,
    fontFamily: INTER_FONT,
  },
  countryHostBadge: {
    backgroundColor: '#16A34A',
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginLeft: 4,
  },
  countryHostBadgeText: {
    fontSize: 8.5,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.3,
    fontFamily: INTER_FONT,
  },
  countryRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  countryDownloads: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.1,
    fontFamily: INTER_FONT,
  },
  countryPctBadge: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 5.5,
    paddingVertical: 1.5,
    borderRadius: 4,
    fontFamily: INTER_FONT,
  },
  countryProgressBar: {
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
  },
  countryProgressFill: {
    height: '100%',
    backgroundColor: '#4F46E5',
    borderRadius: 2.5,
  },

  // ─── Graphics & Activity Graph Card ─────────────────────────────────────────
  statsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  liveIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16A34A',
  },
  liveText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#16A34A',
    letterSpacing: 0.5,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  statBox: {
    flex: 1,
    minWidth: 0,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  statVal: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  statLbl: {
    fontSize: 9,
    color: '#64748B',
    marginTop: 2,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    textAlign: 'center',
  },

  // ─── Panel Cards ────────────────────────────────────────────────────────────
  panelCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  panelHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  panelHeader: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    flexShrink: 1,
  },
  panelHeaderBadge: {
    fontSize: 9,
    fontWeight: '700',
    color: '#64748B',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  btnRow: {
    flexDirection: 'row',
    gap: 8,
  },
  gridBtn: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1.2,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 8,
    backgroundColor: '#FFFFFF',
  },
  btnText: {
    fontSize: 11.5,
    fontWeight: '700',
    textAlign: 'center',
    flexShrink: 1,
  },
  fullWidthBtn: {
    width: '100%',
    minHeight: 42,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 9,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  fullWidthBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
    textAlign: 'center',
    flexShrink: 1,
  },

  // ─── Static Footer Action Bar ───────────────────────────────────────────────
  staticFooterContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 26 : 14,
    gap: 6,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.06,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  footerButton: {
    width: '100%',
    minHeight: 46,
    borderRadius: 13,
    backgroundColor: '#5C2D91',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 8,
    ...Platform.select({
      ios: {
        shadowColor: '#5C2D91',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  footerButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },

  // ─── Info & Code Snippet Rows ───────────────────────────────────────────────
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 8,
  },
  infoLabel: {
    fontSize: 11.5,
    color: '#64748B',
    fontWeight: '600',
    flexShrink: 1,
  },
  infoValue: {
    fontSize: 11.5,
    color: '#0F172A',
    fontWeight: '700',
    textAlign: 'right',
    flexShrink: 1,
  },
  codeSnippet: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  codeText: {
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 11.5,
    color: '#38BDF8',
    fontWeight: '600',
    flexShrink: 1,
  },

  // ─── Details Screen Buttons ─────────────────────────────────────────────────
  detailsLogBtn: {
    backgroundColor: '#059669',
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    gap: 8,
  },
  detailsBackBtn: {
    backgroundColor: '#475569',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    gap: 8,
  },

  // ─── Reusable Layout & Typography Utilities ─────────────────────────────────
  flexShrink1: { flexShrink: 1 },
  rowAlignCenterGap6: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  rowAlignCenterGap4: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  rowBetweenCenter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  gap6: { gap: 6 },
  gap8: { gap: 8 },
  gap2Mt4: { gap: 2, marginTop: 4 },
  gap8Mt4: { gap: 8, marginTop: 4 },
  mt4: { marginTop: 4 },
  headerBadgeText: { marginLeft: 4 },

  // ─── Live Activity Telemetry Card Styles ───────────────────────────────────
  telemetryBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingTop: 8,
    paddingBottom: 4,
    paddingHorizontal: 8,
    overflow: 'hidden',
  },
  telemetryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  telemetryTextLeft: { fontSize: 10, fontWeight: '700', color: '#64748B' },
  telemetryTextIndigo: { color: '#4F46E5' },
  telemetryTextGreen: { fontSize: 10, fontWeight: '700', color: '#16A34A' },
  telemetryAxisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 2,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  telemetryAxisLabel: { fontSize: 9, color: '#94A3B8', fontWeight: '700' },
  telemetryAxisLabelNow: { fontSize: 9, color: '#4F46E5', fontWeight: '800' },
  eventBreakdownTitle: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#0F172A',
    textTransform: 'uppercase',
  },
  eventBreakdownSubtitle: { fontSize: 10, color: '#64748B', fontWeight: '600' },
  distributionBar: {
    flexDirection: 'row',
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: '#E2E8F0',
  },
  barApi: { backgroundColor: '#4F46E5' },
  barLog: { backgroundColor: '#F59E0B' },
  barAnalytics: { backgroundColor: '#0D9488' },
  barEmpty: { flex: 1, backgroundColor: '#CBD5E1' },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  legendDotApi: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#4F46E5' },
  legendTextApi: { fontSize: 10, fontWeight: '700', color: '#4F46E5' },
  legendDotLog: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#F59E0B' },
  legendTextLog: { fontSize: 10, fontWeight: '700', color: '#D97706' },
  legendDotAnalytics: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#0D9488' },
  legendTextAnalytics: { fontSize: 10, fontWeight: '700', color: '#0D9488' },
  legendDotStore: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#7C3AED' },
  legendTextStore: { fontSize: 10, fontWeight: '700', color: '#7C3AED' },
  textApiColor: { color: '#4F46E5' },
  textLogColor: { color: '#D97706' },
  textAnalyticsColor: { color: '#0D9488' },
  textStoreColor: { color: '#7C3AED' },

  // ─── Card Variations & Badges ───────────────────────────────────────────────
  panelCardCrash: { borderColor: '#FECDD3' },
  panelHeaderCrash: { color: '#E11D48' },
  panelHeaderBadgeCrash: { backgroundColor: '#FFE4E6', color: '#BE123C' },
  panelHeaderBadgeNpm: { backgroundColor: '#DCFCE7', color: '#16A34A', fontWeight: '800' },
  panelHeaderBadgeGithub: { backgroundColor: '#F3E8FF', color: '#5C2D91', fontWeight: '800' },
  metricsStrip: { flexDirection: 'row', gap: 8, marginTop: 2 },
  statBoxPv8: { paddingVertical: 8 },
  statValPurple: { color: '#5C2D91', fontSize: 14 },
  statValGreen: { color: '#16A34A', fontSize: 14 },
  statValBlue: { color: '#0284C7', fontSize: 14 },
  statValDark: { color: '#0F172A', fontSize: 14 },
  statValRed: { color: '#DC2626', fontSize: 14 },
  infoValuePurple: { color: '#5C2D91' },
  infoValueGreen: { color: '#16A34A' },
  infoValueAmber: { color: '#D97706' },
  infoValueIndigo: { color: '#6366F1' },
  featureBulletText: { fontSize: 12, color: '#334155', lineHeight: 18 },
  featureBulletBold: { fontWeight: '700' },
});
